In [1]:
# Import the modules
import numpy as np
import pandas as pd
from pathlib import Path
from sklearn.metrics import balanced_accuracy_score, confusion_matrix, classification_report

---

## Split the Data into Training and Testing Sets

### Step 1: Read the `lending_data.csv` data from the `Resources` folder into a Pandas DataFrame.

In [2]:
# Read the CSV file from the Resources folder into a Pandas DataFrame
lending_data = pd.read_csv(
    Path("Resources/lending_data.csv"))

# Review the DataFrame
lending_data.head()

loan_size  interest_rate  borrower_income  debt_to_income  num_of_accounts  \
0    10700.0          7.672            52800        0.431818                5   
1     8400.0          6.692            43600        0.311927                3   
2     9000.0          6.963            46100        0.349241                3   
3    10700.0          7.664            52700        0.430740                5   
4    10800.0          7.698            53000        0.433962                5   

   derogatory_marks  total_debt  loan_status  
0                 1       22800            0  
1                 0       13600            0  
2                 0       16100            0  
3                 1       22700            0  
4                 1       23000            0

In [3]:
lending_data.shape

(77536, 8)

### Step 2: Create the labels set (`y`)  from the “loan_status” column, and then create the features (`X`) DataFrame from the remaining columns.

In [4]:
# Separate the data into labels and features
# Separate the y variable, the labels
y = lending_data["loan_status"]

# Separate the X variable, the features
X = lending_data.drop(columns=["loan_status"])

In [5]:
# Review the y variable Series
y[:5]

0    0
1    0
2    0
3    0
4    0
Name: loan_status, dtype: int64

In [6]:
# Review the X variable DataFrame
X[:5]

loan_size  interest_rate  borrower_income  debt_to_income  num_of_accounts  \
0    10700.0          7.672            52800        0.431818                5   
1     8400.0          6.692            43600        0.311927                3   
2     9000.0          6.963            46100        0.349241                3   
3    10700.0          7.664            52700        0.430740                5   
4    10800.0          7.698            53000        0.433962                5   

   derogatory_marks  total_debt  
0                 1       22800  
1                 0       13600  
2                 0       16100  
3                 1       22700  
4                 1       23000

In [7]:
# cheking the X dataframe
X.shape

(77536, 7)

### Step 3: Check the balance of the labels variable (`y`) by using the `value_counts` function.

In [8]:
# Check the balance of our target values
y.value_counts()

loan_status
0    75036
1     2500
Name: count, dtype: int64

### Step 4: Split the data into training and testing datasets by using `train_test_split`.

In [9]:
# Import the train_test_learn module
from sklearn.model_selection import train_test_split

In [10]:
# Split the data using train_test_split
# Assign a random_state of 1 to the function
X_train, X_test, y_train, y_test = train_test_split(X,y,random_state = 1)

---

## Create a Logistic Regression Model with the Original Data

###  Step 1: Fit a logistic regression model by using the training data (`X_train` and `y_train`).

In [11]:
# Import the LogisticRegression module from SKLearn
from sklearn.linear_model import LogisticRegression

# Instantiate the Logistic Regression model
# Assign a random_state parameter of 1 to the model
classifier = LogisticRegression(solver = 'lbfgs', random_state = 1)
classifier

# Fit the model using training data
classifier.fit(X_train, y_train)

c:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(random_state=1)

In [12]:
# Score the model
print(f"Training Data Score: {classifier.score(X_train, y_train)}")
print(f"Testing Data Score: {classifier.score(X_test, y_test)}")

Training Data Score: 0.9929323153115972
Testing Data Score: 0.9924680148576145


### Step 2: Save the predictions on the testing data labels by using the testing feature data (`X_test`) and the fitted model.

In [13]:
# Make a prediction using the testing data
testing_predictions = classifier.predict(X_test)
testing_predictions

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [15]:
#Creating a dataframe of predicted and actual data
predict_tested_df = pd.DataFrame({"Prediction": testing_predictions, "Actual": y_test})
predict_tested_df.head()

Prediction  Actual
60914           0       0
36843           0       0
1966            0       0
70137           0       0
27237           0       0

### Step 3: Evaluate the model’s performance by doing the following:

* Calculate the accuracy score of the model.

* Generate a confusion matrix.

* Print the classification report.

In [17]:
from sklearn.metrics import balanced_accuracy_score

In [18]:
# Print the balanced_accuracy score of the model
score = balanced_accuracy_score(y_test, testing_predictions)
score

0.967989851522121

In [19]:
from sklearn.metrics import accuracy_score

In [20]:
# Print the accuracy score of the model
accuracy_score(y_test,testing_predictions)

0.9924680148576145

In [21]:
# Generate a confusion matrix for the model
test_matrix = confusion_matrix(y_test, testing_predictions)

# Print the confusion matrix for the testing data
print(test_matrix)

[[18655   110]
 [   36   583]]


In [22]:
# Print the classification report for the model
testing_report = classification_report(y_test, testing_predictions)

# Print the testing classification report
print(testing_report)

              precision    recall  f1-score   support

           0       1.00      0.99      1.00     18765
           1       0.84      0.94      0.89       619

    accuracy                           0.99     19384
   macro avg       0.92      0.97      0.94     19384
weighted avg       0.99      0.99      0.99     19384



### Step 4: Answer the following question.

**Question:** How well does the logistic regression model predict both the `0` (healthy loan) and `1` (high-risk loan) labels?

**Answer:** The explanation to logistic regression model predicting  both the `0` (healthy loan) and `1` (high-risk loan) labels are given as following:

**Precision** 
- For 0 (healthy loan): The precision is 1.00, indicating that when the model predicts a loan as healthy, it is correct 100% of the time.
- For 1 (high-risk loan): The precision is 0.84, meaning that when the model predicts a loan as high-risk, it is correct 84% of the time.

**Recall**:
- For 0 (healthy loan): The recall is 0.99, which means the model successfully identifies 99% of all healthy loans.
- For 1 (high-risk loan): The recall is 0.94, indicating that the model identifies 94% of all high-risk loans correctly.

**F1-Score**:
- For 0 (healthy loan): The F1-score is 1.00, showing a perfect balance between precision and recall for healthy loan predictions.
- For 1 (high-risk loan): The F1-score is 0.89, which is quite high and indicates a good balance between precision and recall for high-risk loan predictions.

**Accuracy**:
- The overall accuracy of the model is 0.99, suggesting that the model correctly predicts the label (whether healthy or high-risk) for 99% of the loans in the dataset.

**Macro Average**:
- The macro average for precision, recall, and F1-score are 0.92, 0.97, and 0.94, respectively. These numbers suggest the model performs quite well across both categories,i.e, healthy and high risk loan, without significant bias towards one class.

**Weighted Average**:
- The weighted averages for precision, recall, and F1-score are very high (0.99 for all), reflecting the model's overall accuracy considering the imbalance between the two classes (there are far more healthy loans than high-risk ones in the dataset).
In summary, we can say that the logistic regression model performs excellently in predicting healthy loans with almost perfect precision, recall, and F1-score. It also does a good job at identifying high-risk loans, though there's a slight drop in precision compared to healthy loans. This is expected as predicting high-risk loans is inherently more challenging due to their less frequent occurrence and potentially more complex patterns. However, the high recall for high-risk loans is particularly noteworthy, as it suggests the model is very capable of catching most of the high-risk loans, which is crucial for risk management purposes. Overall, the model is quite effective at distinguishing between healthy and high-risk loans.

---

## Predict a Logistic Regression Model with Resampled Training Data

### Step 1: Use the `RandomOverSampler` module from the imbalanced-learn library to resample the data. Be sure to confirm that the labels have an equal number of data points. 

In [23]:
!pip install imbalanced-learn



[notice] A new release of pip is available: 23.3.2 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [24]:
# Import the RandomOverSampler module form imbalanced-learn
from imblearn.over_sampling import RandomOverSampler


In [25]:
# Instantiate the random oversampler model
# # Assign a random_state parameter of 1 to the model
random_sampler = RandomOverSampler(random_state = 1)
random_sampler

# Fit the original training data to the random_oversampler model
X_resampled, y_resampled = random_sampler.fit_resample(X, y)

# Now, X_resampled and y_resampled contain the oversampled dataset which we can use to train our model.


In [26]:
# Count the distinct values of the resampled labels data
unique, counts = np.unique(y_resampled, return_counts=True)
resampled_counts = dict(zip(unique, counts))

print("Counts of resampled labels:", resampled_counts)

Counts of resampled labels: {0: 75036, 1: 75036}


### Step 2: Use the `LogisticRegression` classifier and the resampled data to fit the model and make predictions.

In [27]:
# Instantiate the Logistic Regression model
# Assign a random_state parameter of 1 to the model
classifier_random = LogisticRegression(solver = 'lbfgs', random_state = 1)

# Fit the model using the resampled training data
classifier_random.fit(X_resampled, y_resampled)

# Make a prediction using the testing data
predictions_random = classifier_random.predict(X_resampled)
predictions_random 

array([0, 0, 0, ..., 1, 1, 1], dtype=int64)

### Step 3: Evaluate the model’s performance by doing the following:

* Calculate the accuracy score of the model.

* Generate a confusion matrix.

* Print the classification report.

In [28]:
# Print the balanced_accuracy score of the model 
random_score = balanced_accuracy_score(y_resampled, predictions_random )
random_score

0.9944360040513887

In [29]:
# Generate a confusion matrix for the model
random_confusion_matrix = confusion_matrix(y_resampled, predictions_random )

# Print the confusion matrix for the testing data
print(random_confusion_matrix)

[[74604   432]
 [  403 74633]]


In [30]:
# Print the classification report for the model
random_report = classification_report(y_resampled, predictions_random )

# Print the testing classification report
print(random_report)

              precision    recall  f1-score   support

           0       0.99      0.99      0.99     75036
           1       0.99      0.99      0.99     75036

    accuracy                           0.99    150072
   macro avg       0.99      0.99      0.99    150072
weighted avg       0.99      0.99      0.99    150072



### Step 4: Answer the following question

**Question:** How well does the logistic regression model, fit with oversampled data, predict both the `0` (healthy loan) and `1` (high-risk loan) labels?

**Answer:** The classification report  for our newly made logistic regression model, trained on oversampled data, shows excellent performance across all metrics for both 0 (healthy loan) and 1 (high-risk loan) labels. Here's a breakdown of the performance metrics:
**Precision**:
- For 0 (healthy loan): The precision is 0.99, indicating that 99% of the loans predicted as healthy by the model are indeed healthy.
- For 1 (high-risk loan): The precision is also 0.99, meaning that 99% of the loans predicted as high-risk by the model are indeed high-risk.

**Recall**
- For 0 (healthy loan): The recall is 0.99, which means the model correctly identifies 99% of all actual healthy loans.
- For 1 (high-risk loan): The recall is also 0.99, indicating that the model correctly identifies 99% of all actual high-risk loans.

**F1-Score**
- For both classes: The F1-score, which is a harmonic mean of precision and recall, is 0.99 for both classes. This suggests a balanced performance between precision and recall, indicating that the model is equally good at identifying both healthy and high-risk loans.

**Accuracy**
- The overall accuracy of the model is 0.99, meaning it correctly predicts the loan status (healthy or high-risk) for 99% of the loans in the dataset.

**Macro Avg and Weighted Avg**:
Both the macro and weighted averages for precision, recall, and F1-score are 0.99. The macro average treats both classes equally, indicating strong performance across both classes regardless of their size. The weighted average accounts for class imbalance, which, due to oversampling making the classes equal in size, aligns with the macro average.

The logistic regression model, after being trained on oversampled data, performs exceptionally well in predicting both healthy and high-risk loans. The model demonstrates high precision and recall for both classes, which is particularly noteworthy given the initial class imbalance. Oversampling has effectively mitigated the imbalance issue, allowing the model to learn equally from both classes and thus perform well on both. This indicates a successful application of oversampling to improve model performance on an imbalanced dataset.